<?php

/**
 * @file
 * Configuration module for islandora_solr_search.module
 */

/**
 * Implementations of hook_init()
 * Including css for the admin page.
 */
 
function islandora_solr_custom_init() {
  // adds css. I should look for an alternative place to load this because hook_init() will load this on every page.
  drupal_add_css(drupal_get_path('module', 'islandora_solr_custom') .'/css/islandora_solr_custom.css');

  // add the .inc files
  module_load_include('inc', 'islandora_solr_custom', 'islandora_solr_custom.admin');
  //module_load_include('inc', 'islandora_solr_custom', 'includes/IslandoraSolrResultsCSVcustom');
}




/**
 * Implementation of hook_help()
 */

function islandora_solr_custom_help($path, $arg) {

  switch ($path) {
    case 'admin/help#islandora_solr_config':
      return t('The islandora_solr_custom module provides a display type for the islandora_solr_search module. It automatically looks for the fields set for display in !solrconfig and outputs the fields in the order that they are defined in the requestHandler. Islandora_solr_custom will look at the settings set at !page to find solrconfig.xml and the requestHandler. You can quickly customize the output style of your search results by changing the settings in the admin section or you can take full control by overriding the template file.', array('!page' => l(t("Islandora_solr_search configuration page"), 'admin/settings/islandora_solr_search'), '!solrconfig' => l(t('solrconfig.xml'), 'http://wiki.apache.org/solr/SolrConfigXml') ));
    case 'admin/settings/islandora_solr_search/custom':
      return t('The islandora_solr_custom module provides a display type for the islandora_solr_search module. It automatically looks for the fields set for display in !solrconfig and outputs the fields in the order that they are defined in the requestHandler. Islandora_solr_custom will look at the settings set at !page to find solrconfig.xml and the requestHandler. You can quickly customize the output style of your search results by changing the settings in the admin section or you can take full control by overriding the template file.', array('!page' => l(t("Islandora_solr_search configuration page"), 'admin/settings/islandora_solr_search'), '!solrconfig' => l(t('solrconfig.xml'), 'http://wiki.apache.org/solr/SolrConfigXml') ));
  }
}


/**
 * Implementation of hook_menu()
 */
 
function islandora_solr_custom_menu() {
  $items['admin/settings/islandora_solr_search/config'] = array(
    'title' => 'Islandora Solr Client',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file path' => drupal_get_path('module', 'islandora_solr_search'),
    'weight' => -1,
  );
  $items['admin/settings/islandora_solr_search/custom'] = array(
    'title' => 'Islandora Solr customization',
    'description' => 'Customizing Islandora Solr output results',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_solr_custom_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'islandora_solr_custom.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}



/**
 * Implementation of hook_theme()
 */
 
function islandora_solr_custom_theme() {
  // set path
  $path = drupal_get_path('module', 'islandora_solr_custom') . '/theme';
  $file = 'islandora_solr_custom.theme.inc';
  
  return array(
    'islandora_solr_custom' => array(
      'path' => $path,
      'file' => $file,
      'template' => 'islandora-solr-custom',
      'arguments' => array('results_raw' => NULL),
    ),
    'islandora_solr_custom_admin_settings' => array(
      'path' => $path,
      'file' => $file,
      'arguments' => array('form' => NULL),
    ),
    'islandora_solr_custom_switch' => array(
      'path' => $path,
      'file' => $file,
      'arguments' => array('curr_url' => NULL),
    ),
    'islandora_solr_custom_table' => array(
      'path' => $path,
      'file' => $file,
      'arguments' => array('db_values' => NULL, 'results' => NULL),
    ),
    'islandora_solr_custom_rss_item' => array(
      'path' => $path,
      'file' => $file,
      'arguments' => array('doc' => NULL, 'feed' => NULL),
    ),
    'islandora_solr_custom_rss_channel' => array(
      'path' => $path,
      'file' => $file,
      'arguments' => array('query' => NULL, 'feed' => NULL),
    ),
  );
}
 
 
 


/**
 * Implements hook_islandora_solr_primary_display()
 */
function islandora_solr_custom_islandora_solr_primary_display() {
  return array(
    // 'machine-name' = array(
    //   'name' => 'Human Readable Name',
    //   'module' => 'module_name',
    //   'file' => 'FileName.inc',
    //   'class' => 'ClassName',
    //   'function' => 'function_name',
    //   'description' => 'A description of the display profile',
    // );
    'custom' => array(
      'name' => t('Custom'),
      'module' => 'islandora_solr_custom',
      'file' => '/includes/IslandoraSolrResultsCustom.inc',
      'class' => "IslandoraSolrResultsCustom",
      'function' => "displayResults",
      'description' => t("Take full controll over the markup of the Solr results."),
    ),
  );
}


/**
 * Implements hook_islandora_solr_secondary_display()
 */
function islandora_solr_custom_islandora_solr_secondary_display() {
  return array(
    'csv_custom' => array(
      'name' => t('CSV custom'),
      'module' => 'islandora_solr_custom',
      'file' => '/includes/IslandoraSolrResultsCSVcustom.inc',
      'class' => 'IslandoraSolrResultsCSVcustom',
      'function' => 'printCSV',
      'description' => 'Download complete resultset as a CSV Spreadsheet',
      'logo' => '<img src="http://www.stdicon.com/crystal/application/vnd.ms-excel?size=32" class="islandora_solr_secondary_display_icon">',
    ),
    'rss' => array(
      'name' => t('RSS'),
      'module' => 'islandora_solr_custom',
      'file' => '/includes/IslandoraSolrResultsRSS.inc',
      'class' => 'IslandoraSolrResultsRSS',
      'function' => 'printRSS',
      'description' => 'Parse a complete resultset as an RSS feed',
      'logo' => '<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/18px-Feed-icon.svg.png" class="islandora_solr_secondary_display_icon">',
    ),
  );
}


